### ISSUE TITLE
Request for presence

### ISSUE THREAD

**Issue by ctubio** [bbs4us/sks-bootstrap-index#1]
Hello @bbs4us,
im collecting somehow web interfaces for keyservers, and i found yours quite interesting with the mobile version!

Therefore i was wondering if you let me add your project https://github.com/bbs4us/sks-bootstrap-index as a git submodule in https://github.com/ctubio/php-proxy-keyserver/tree/master/skin?

Otherwise i can add a text file with a link to your project (nice plan b)
Or otherwise, i can just do nothing (nice plan c)

What do you think?

Thank you for your time,

**Comment by bbs4us** [comment]
Certainly, just add it as a submodule!

**Comment by ctubio** [comment]
Thank you (alot!) :o]]]

and Best Regards from Catalonia,
